#Docker test
version: '3.1'

services:
  webserver:
    build: ./docker/webserver
    image: myinsead_dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html
    links:
      - db
      - redis

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=myinsead_dev
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./docker/db/redis:/data
